---
- name: Provision VM from template
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
#    datacenter: Default
    
  tasks:

  - name: Create and run RHEL VM from template
    ovirt_vm:
      name: "{{ vm_name | default('10_ap_ceenter_test', true) }}"
      template: default_template
      cluster: "{{ cluster | default('Default', true) }}"
      memory: "{{vm_memory | default('1GiB', true) }}"
      high_availability: true
      description: "{{ description | default(omit) }}"
      state: running
      wait: yes
